"""scope recommendation identity_key uniqueness to active rows

Fixes a bug caught by live-running the scheduler against the real simulator: identity_key was
globally unique, but the same condition legitimately recurs after a recommendation resolves (a
lone worker leaves and returns, an ESD flag clears and re-trips), so the very next occurrence
crashed the risk-evaluation tick with a duplicate-key violation. Replaces the plain unique
index with one scoped to non-resolved rows only, so each recurrence gets its own row.

Revision ID: 347e518cce2b
Revises: 6e0775e4f493
Create Date: 2026-07-14 21:45:15.387885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347e518cce2b'
down_revision: Union[str, Sequence[str], None] = '6e0775e4f493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_identity_key'), table_name='recommendations')
    op.create_index(op.f('ix_recommendations_identity_key'), 'recommendations', ['identity_key'], unique=False)
    op.create_index('ux_recommendations_identity_key_active', 'recommendations', ['identity_key'], unique=True, postgresql_where=sa.text("state != 'resolved'"), sqlite_where=sa.text("state != 'resolved'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_recommendations_identity_key_active', table_name='recommendations', postgresql_where=sa.text("state != 'resolved'"), sqlite_where=sa.text("state != 'resolved'"))
    op.drop_index(op.f('ix_recommendations_identity_key'), table_name='recommendations')
    op.create_index(op.f('ix_recommendations_identity_key'), 'recommendations', ['identity_key'], unique=True)
    # ### end Alembic commands ###
