"""recommendation engine

Adds the Recommendation Engine's persistent footprint: the recommendations table (stateful
lifecycle rows reconciled from RiskAssessment on every risk-evaluation tick, keyed by a stable
zone_id + template_id identity), and an optional recommendation_id FK on events so
acknowledge/resolve transitions are linked into the existing audit trail. Purely additive.

Revision ID: 6e0775e4f493
Revises: 2b2abe20fb7f
Create Date: 2026-07-14 21:32:11.287318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e0775e4f493'
down_revision: Union[str, Sequence[str], None] = '2b2abe20fb7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('identity_key', sa.String(length=150), nullable=False),
    sa.Column('template_id', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('action_text', sa.String(length=500), nullable=False),
    sa.Column('expected_outcomes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rationale', sa.String(length=500), nullable=False),
    sa.Column('source_rule_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('target_entity', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('engine_version', sa.String(length=30), nullable=False),
    sa.Column('generation_source', sa.String(length=20), nullable=False),
    sa.Column('first_generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_category'), 'recommendations', ['category'], unique=False)
    op.create_index(op.f('ix_recommendations_identity_key'), 'recommendations', ['identity_key'], unique=True)
    op.create_index(op.f('ix_recommendations_last_seen_at'), 'recommendations', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_recommendations_priority'), 'recommendations', ['priority'], unique=False)
    op.create_index(op.f('ix_recommendations_state'), 'recommendations', ['state'], unique=False)
    op.create_index(op.f('ix_recommendations_template_id'), 'recommendations', ['template_id'], unique=False)
    op.create_index(op.f('ix_recommendations_zone_id'), 'recommendations', ['zone_id'], unique=False)
    op.add_column('events', sa.Column('recommendation_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_events_recommendation_id'), 'events', ['recommendation_id'], unique=False)
    op.create_foreign_key(None, 'events', 'recommendations', ['recommendation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_recommendation_id'), table_name='events')
    op.drop_column('events', 'recommendation_id')
    op.drop_index(op.f('ix_recommendations_zone_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_template_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_state'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_priority'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_last_seen_at'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_identity_key'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_category'), table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###
