"""initial schema

Revision ID: 7a9bf0e8fad2
Revises: 
Create Date: 2026-07-09 17:41:59.717346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a9bf0e8fad2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plants_code'), 'plants', ['code'], unique=True)
    op.create_table('zones',
    sa.Column('plant_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('zone_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('grid_row', sa.Integer(), nullable=True),
    sa.Column('grid_col', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_code'), 'zones', ['code'], unique=True)
    op.create_index(op.f('ix_zones_plant_id'), 'zones', ['plant_id'], unique=False)
    op.create_index(op.f('ix_zones_zone_type'), 'zones', ['zone_type'], unique=False)
    op.create_table('equipment',
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('tag_number', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('equipment_type', sa.String(length=40), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model_number', sa.String(length=120), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('criticality', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_equipment_type'), 'equipment', ['equipment_type'], unique=False)
    op.create_index(op.f('ix_equipment_tag_number'), 'equipment', ['tag_number'], unique=True)
    op.create_index(op.f('ix_equipment_zone_id'), 'equipment', ['zone_id'], unique=False)
    op.create_table('workers',
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('employment_status', sa.String(length=30), nullable=False),
    sa.Column('shift', sa.String(length=20), nullable=True),
    sa.Column('primary_zone_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_employee_id'), 'workers', ['employee_id'], unique=True)
    op.create_index(op.f('ix_workers_primary_zone_id'), 'workers', ['primary_zone_id'], unique=False)
    op.create_index(op.f('ix_workers_role'), 'workers', ['role'], unique=False)
    op.create_table('permits',
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=True),
    sa.Column('permit_number', sa.String(length=30), nullable=False),
    sa.Column('permit_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_by_id', sa.Uuid(), nullable=False),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permits_approved_by_id'), 'permits', ['approved_by_id'], unique=False)
    op.create_index(op.f('ix_permits_equipment_id'), 'permits', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_permits_permit_number'), 'permits', ['permit_number'], unique=True)
    op.create_index(op.f('ix_permits_permit_type'), 'permits', ['permit_type'], unique=False)
    op.create_index(op.f('ix_permits_requested_by_id'), 'permits', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_permits_status'), 'permits', ['status'], unique=False)
    op.create_index(op.f('ix_permits_zone_id'), 'permits', ['zone_id'], unique=False)
    op.create_table('sensors',
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=True),
    sa.Column('tag_number', sa.String(length=30), nullable=False),
    sa.Column('sensor_type', sa.String(length=40), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_equipment_id'), 'sensors', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_sensors_sensor_type'), 'sensors', ['sensor_type'], unique=False)
    op.create_index(op.f('ix_sensors_tag_number'), 'sensors', ['tag_number'], unique=True)
    op.create_index(op.f('ix_sensors_zone_id'), 'sensors', ['zone_id'], unique=False)
    op.create_table('events',
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('equipment_id', sa.Uuid(), nullable=True),
    sa.Column('permit_id', sa.Uuid(), nullable=True),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_equipment_id'), 'events', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_events_permit_id'), 'events', ['permit_id'], unique=False)
    op.create_index(op.f('ix_events_recorded_by_id'), 'events', ['recorded_by_id'], unique=False)
    op.create_index(op.f('ix_events_zone_id'), 'events', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_zone_id'), table_name='events')
    op.drop_index(op.f('ix_events_recorded_by_id'), table_name='events')
    op.drop_index(op.f('ix_events_permit_id'), table_name='events')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_equipment_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_sensors_zone_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_tag_number'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_sensor_type'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_equipment_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_permits_zone_id'), table_name='permits')
    op.drop_index(op.f('ix_permits_status'), table_name='permits')
    op.drop_index(op.f('ix_permits_requested_by_id'), table_name='permits')
    op.drop_index(op.f('ix_permits_permit_type'), table_name='permits')
    op.drop_index(op.f('ix_permits_permit_number'), table_name='permits')
    op.drop_index(op.f('ix_permits_equipment_id'), table_name='permits')
    op.drop_index(op.f('ix_permits_approved_by_id'), table_name='permits')
    op.drop_table('permits')
    op.drop_index(op.f('ix_workers_role'), table_name='workers')
    op.drop_index(op.f('ix_workers_primary_zone_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_employee_id'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_equipment_zone_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_tag_number'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_equipment_type'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_zones_zone_type'), table_name='zones')
    op.drop_index(op.f('ix_zones_plant_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_code'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_plants_code'), table_name='plants')
    op.drop_table('plants')
    # ### end Alembic commands ###
