"""simulation state: worker location, sensor latest reading, readings table

Revision ID: dcd6c2406a80
Revises: 7a9bf0e8fad2
Create Date: 2026-07-09 23:09:56.008165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd6c2406a80'
down_revision: Union[str, Sequence[str], None] = '7a9bf0e8fad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_readings',
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_recorded_at'), 'sensor_readings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_sensor_readings_sensor_id'), 'sensor_readings', ['sensor_id'], unique=False)
    op.add_column('sensors', sa.Column('last_value', sa.Float(), nullable=True))
    op.add_column('sensors', sa.Column('last_reading_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workers', sa.Column('current_zone_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_workers_current_zone_id'), 'workers', ['current_zone_id'], unique=False)
    op.create_foreign_key(
        'fk_workers_current_zone_id_zones', 'workers', 'zones', ['current_zone_id'], ['id']
    )
    # Workers start wherever they are stationed.
    op.execute('UPDATE workers SET current_zone_id = primary_zone_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_workers_current_zone_id_zones', 'workers', type_='foreignkey')
    op.drop_index(op.f('ix_workers_current_zone_id'), table_name='workers')
    op.drop_column('workers', 'current_zone_id')
    op.drop_column('sensors', 'last_reading_at')
    op.drop_column('sensors', 'last_value')
    op.drop_index(op.f('ix_sensor_readings_sensor_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_recorded_at'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    # ### end Alembic commands ###
